Repository AgoraIO-Extensions/react-native-agora, pull requests merged in 2023-11, with the labels that each got.

#729 [AUTO] Generate codes by terra
  src/AgoraBase.ts
  src/IAgoraMediaPlayer.ts
  src/IAgoraRtcEngine.ts
Labels: ci:terra-update

#734 [AUTO] Update dependencies
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/dep.yml
  .github/workflows/doc.yml
  .github/workflows/gitleaks.yml
  .github/workflows/publish.yml
  .github/workflows/terra.yml
  .github/workflows/typedoc.yml
  android/build.gradle
  example/ios/Podfile
  react-native-agora.podspec
Labels: ci:dep-update

#735 feat: support native 4.2.6
  .github/actions/setup/action.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/dep.yml
  .github/workflows/doc.yml
  .github/workflows/gitleaks.yml
  .github/workflows/publish.yml
  .github/workflows/terra.yml
  .github/workflows/typedoc.yml
  android/build.gradle
  example/ios/AgoraRtcNgExample.xcodeproj/project.pbxproj
  example/ios/Podfile
  example/ios/Podfile.lock
  package.json
  react-native-agora.podspec
  scripts/bootstrap.cjs
Labels: ci:dep-update

#744 [AUTO] Generate comments by iris-doc
  src/AgoraBase.ts
  src/AgoraMediaBase.ts
  src/IAgoraLog.ts
  src/IAgoraMediaEngine.ts
  src/IAgoraMediaPlayer.ts
  src/IAgoraRtcEngine.ts
  src/IAgoraRtcEngineEx.ts
Labels: ci:doc-update

#745 [AUTO] Generate codes by terra
  src/AgoraBase.ts
  src/AgoraMediaBase.ts
  src/AgoraMediaPlayerTypes.ts
  src/IAgoraMediaPlayer.ts
  src/IAgoraMediaPlayerSource.ts
  src/IAgoraMusicContentCenter.ts
  src/IAgoraRhythmPlayer.ts
  src/IAgoraRtcEngine.ts
  src/IAgoraRtcEngineEx.ts
  src/IAgoraSpatialAudio.ts
  src/impl/AgoraMediaBaseImpl.ts
  src/impl/IAgoraMediaPlayerImpl.ts
  src/impl/IAgoraMediaPlayerSourceImpl.ts
  src/impl/IAgoraMusicContentCenterImpl.ts
  src/impl/IAgoraRtcEngineExImpl.ts
  src/impl/IAgoraRtcEngineImpl.ts
  src/impl/IAgoraSpatialAudioImpl.ts
  src/ti/AgoraMediaBase-ti.ts
  src/ti/IAgoraMediaPlayerSource-ti.ts
  src/ti/IAgoraMusicContentCenter-ti.ts
  src/ti/IAgoraRtcEngine-ti.ts
Labels: ci:terra-update

#746 [AUTO] Update dependencies
  android/build.gradle
  example/ios/Podfile
  example/ios/Podfile.lock
  react-native-agora.podspec
Labels: ci:dep-update

#747 [AUTO] Generate codes by terra
  src/IAgoraSpatialAudio.ts
  src/impl/IAgoraSpatialAudioImpl.ts
Labels: ci:terra-update

#749 [AUTO] Generate codes by terra
  src/IAgoraRtcEngine.ts
  src/impl/IAgoraRtcEngineImpl.ts
Labels: ci:terra-update
